#Server Configuration
server:
  port: ${SPRING_PORT:8080}   #Server Port
#Datasource Configuration for MYSQL
spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/practice
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
#CORS Congiurations
cors:
  allowed-origins: "*"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  exposed-headers: "Authorization"
jwt:
  secret: ${JWT_SECRET:"5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"}
  expiration: 1800 # JWT expiration time in seconds (30 minutes)
  header: Authorization  # HTTP header for JWT
  prefix: Bearer  # Prefix for JWT
